# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_metadata.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_metadata_pb2 as user__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63hat_metadata.proto\x12\x07\x63onnect\x1a\x13user_metadata.proto\"y\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\trecipient\x18\x04 \x01(\t\x12&\n\x06status\x18\x05 \x01(\x0e\x32\x16.connect.MessageStatus\"\xcf\x01\n\x04\x43hat\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x11\n\tchat_type\x18\x02 \x01(\t\x12#\n\x0cparticipants\x18\x03 \x03(\x0b\x32\r.connect.User\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\x12&\n\x0clast_message\x18\x06 \x01(\x0b\x32\x10.connect.Message\x12.\n\x0egroup_metadata\x18\x07 \x01(\x0b\x32\x16.connect.GroupMetaData\"\xa4\x01\n\rGroupMetaData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x15\n\rcreation_date\x18\x03 \x01(\t\x12!\n\ncreated_by\x18\x04 \x01(\x0b\x32\r.connect.User\x12\x1d\n\x06\x61\x64mins\x18\x05 \x03(\x0b\x32\r.connect.User\x12\x17\n\x0fprofile_picture\x18\x06 \x01(\t*=\n\rMessageStatus\x12\x08\n\x04SENT\x10\x00\x12\r\n\tDELIVERED\x10\x01\x12\x08\n\x04READ\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\x46\n\x0b\x43hatService\x12\x37\n\rMessageStream\x12\x10.connect.Message\x1a\x10.connect.Message(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGESTATUS']._serialized_start=553
  _globals['_MESSAGESTATUS']._serialized_end=614
  _globals['_MESSAGE']._serialized_start=53
  _globals['_MESSAGE']._serialized_end=174
  _globals['_CHAT']._serialized_start=177
  _globals['_CHAT']._serialized_end=384
  _globals['_GROUPMETADATA']._serialized_start=387
  _globals['_GROUPMETADATA']._serialized_end=551
  _globals['_CHATSERVICE']._serialized_start=616
  _globals['_CHATSERVICE']._serialized_end=686
# @@protoc_insertion_point(module_scope)
