# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_metadata.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13user_metadata.proto\x12\x07\x63onnect\"\xee\x02\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x05 \x01(\t\x12\x19\n\x11profile_image_url\x18\x06 \x01(\t\x12\x14\n\x0cphone_number\x18\x07 \x01(\t\x12\x0b\n\x03\x62io\x18\x08 \x01(\t\x12\x11\n\tis_online\x18\t \x01(\x08\x12\x11\n\thas_story\x18\n \x01(\x08\x12\x11\n\tlast_seen\x18\x0b \x01(\x03\x12\x12\n\ncreated_at\x18\x0c \x01(\x03\x12\x12\n\nlast_login\x18\r \x01(\x03\x12\x10\n\x08group_id\x18\x0e \x03(\t\x12\x12\n\npast_uuids\x18\x0f \x03(\t\x12\x18\n\x10\x62locked_users_id\x18\x10 \x03(\t\x12\x13\n\x0bis_verified\x18\x11 \x01(\x08\x12\x11\n\tis_active\x18\x12 \x01(\x08\x12\x10\n\x08is_staff\x18\x13 \x01(\x08\"\x1a\n\x0bUserRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"+\n\x0cUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.connect.User\"0\n\x11\x43reateUserRequest\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.connect.User\"\x07\n\x05\x45mpty2\xbc\x01\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.connect.UserRequest\x1a\x15.connect.UserResponse\x12?\n\nCreateUser\x12\x1a.connect.CreateUserRequest\x1a\x15.connect.UserResponse\x12\x34\n\tListUsers\x12\x0e.connect.Empty\x1a\x15.connect.UserResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=33
  _globals['_USER']._serialized_end=399
  _globals['_USERREQUEST']._serialized_start=401
  _globals['_USERREQUEST']._serialized_end=427
  _globals['_USERRESPONSE']._serialized_start=429
  _globals['_USERRESPONSE']._serialized_end=472
  _globals['_CREATEUSERREQUEST']._serialized_start=474
  _globals['_CREATEUSERREQUEST']._serialized_end=522
  _globals['_EMPTY']._serialized_start=524
  _globals['_EMPTY']._serialized_end=531
  _globals['_USERSERVICE']._serialized_start=534
  _globals['_USERSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
